FOLDER_NAME_UNZIP = "__CER_TOOL_TEMP_UNZIP__"
FILE_NAME_COMMENT = "__CER_TOOL_TEMP_COMMENT__.txt"

FOLDER_NAME_SUBMISSIONS = "feedback"
FOLDER_NAME_OUTPUT = "out"

MOODLE_SUBMISSION_KEYWORD = "assignsubmission_file"

MOODLE_FEEDBACK_STANDARD_TEXT = "<strong>- TH</strong>"

VERBOSE = True