FOLDER_NAME_TEMP = "__CER_TOOL_TEMP_ZIP_{}__"
FILE_NAME_COMMENT = "__CER_TOOL_TEMP_COMMENT__.txt"

MOODLE_SUBMISSION_KEYWORD = "assignsubmission_file"

MOODLE_FEEDBACK_STANDARD_TEXT = ["<strong>- TH</strong>"]
MOODLE_FEEDBACK_FILENAME_PREFIX = "Feedback"
MOODLE_FEEDBACK_FILENAME_SUFFIX = "TH"
MOODLE_FILE_UPLOAD_LIMIT_BYTES = 25 * 10**6 - 500

VERBOSE = True